cache: bundler
language: ruby
rvm:
  - "2.1"
  - "2.2"
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - jruby-9.0.5.0
  - rbx-2
matrix:
  # Doesn't play well with Rubocop
  allow_failures:
    - rvm: rbx-2
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
